"use client";
import Hider from "@/components/layout/hider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Login from "@/components/login";
import { useState } from "react";
import { Link } from "react-router-dom";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLogin, setIsLogin] = useState(false);

  const handleLogin = () => {
    setIsLogin(true);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Hider />
        {isLogin ? children : <Login setLogin={handleLogin} />}

      </body>
    </html>
  );
}
